# Generated by Django 3.0.8 on 2020-07-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('read_type', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('covid_contact', models.BooleanField()),
                ('birthdate', models.DateTimeField()),
                ('gender', models.BooleanField()),
                ('address', models.TextField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_resgister', models.IntegerField(default=0)),
            ],
        ),
    ]
