# Generated by Django 3.0.8 on 2020-07-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='birthdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='covid_contact',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='gender',
            field=models.BooleanField(null=True),
        ),
    ]
