# Generated by Django 3.0.8 on 2020-07-15 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_auto_20200714_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='user_resgister',
            new_name='user_register',
        ),
    ]
