# Generated by Django 3.0.8 on 2020-07-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='date_visit',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
