# Generated by Django 3.0.8 on 2020-07-10 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_measure', '0002_auto_20200710_2148'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='temperature_measure',
            table='temperature_measure',
        ),
    ]
