# Generated by Django 3.0.8 on 2020-07-15 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_measure', '0003_auto_20200710_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperature_measure',
            old_name='user_resgister',
            new_name='user_register',
        ),
    ]
