# Generated by Django 3.0.8 on 2020-07-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_measure', '0004_auto_20200715_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature_measure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperature_measure',
            name='user_register',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
