# Generated by Django 3.0.8 on 2020-07-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_measure', '0005_auto_20200723_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature_measure',
            name='id_file',
            field=models.CharField(default='0', max_length=250),
        ),
    ]
